name: Build Jellyfin Android

on:
  workflow_dispatch: # lets you trigger manually
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build APK
      run: ./gradlew :app:assembleLibreDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: jellyfin-apk
        path: app/build/outputs/apk/libre/debug/*.apk
